// iOS URL Schemes — comprehensive list
// Sources: Justin Meyers (Medium), phynet/iOS-URL-Schemes (GitHub),
//          ChronSyn/BIG-iOS-URL-SCHEME-LIST (GitHub Gist),
//          Apple Developer docs, bhagyas/app-urls, Tanaschita repo
// Flags: hidden = hidden/private Apple app, deep = has path/params

window.SCHEMES = [

  // ── APPLE SYSTEM & HIDDEN APPS ──────────────────────────────────────────
  { scheme: "airplayreceiver-private://", cat: "Apple Hidden", hidden: true },
  { scheme: "ams-ui://",                  cat: "Apple Hidden", hidden: true },
  { scheme: "ams-ue://",                  cat: "Apple Hidden", hidden: true },
  { scheme: "ams-sdu://",                 cat: "Apple Hidden", hidden: true },
  { scheme: "applerttcall://",            cat: "Apple Hidden", hidden: true },
  { scheme: "carrierspaceauth://",        cat: "Apple Hidden", hidden: true },
  { scheme: "X-DK://",                    cat: "Apple Hidden", hidden: true },
  { scheme: "superbox-audio://",          cat: "Apple Hidden", hidden: true },
  { scheme: "superbox-video://",          cat: "Apple Hidden", hidden: true },
  { scheme: "system-call-controls://",    cat: "Apple Hidden", hidden: true },
  { scheme: "system-screen-sharing://",   cat: "Apple Hidden", hidden: true },
  { scheme: "fido://",                    cat: "Apple Hidden", hidden: true },
  { scheme: "shareablecredentialsuiservice://", cat: "Apple Hidden", hidden: true },
  { scheme: "subcredentialuiservice://",  cat: "Apple Hidden", hidden: true },
  { scheme: "passuiservice://",           cat: "Apple Hidden", hidden: true },
  { scheme: "peopleMessage://",           cat: "Apple Hidden", hidden: true },
  { scheme: "airplayreceiver-private://", cat: "Apple Hidden", hidden: true },
  { scheme: "setup-device-migration://",  cat: "Apple Hidden", hidden: true },
  { scheme: "prefs-prebuddy://",          cat: "Apple Hidden", hidden: true },
  { scheme: "os-beta-updates://",         cat: "Apple Hidden", hidden: true },
  { scheme: "prefs-tvprovider://",        cat: "Apple Hidden", hidden: true },
  { scheme: "prefs-finance-script://",    cat: "Apple Hidden", hidden: true },
  { scheme: "appleprintcenter://",        cat: "Apple Hidden", hidden: true },
  { scheme: "com-apple-mobilesafari-tab://", cat: "Apple Hidden", hidden: true },
  { scheme: "safari-web-extension://",    cat: "Apple Hidden", hidden: true },
  { scheme: "icloud-sharing://",          cat: "Apple Hidden", hidden: true },
  { scheme: "appleiclouddrive://",        cat: "Apple Hidden", hidden: true },
  { scheme: "photos-migrate-iphoto://",   cat: "Apple Hidden", hidden: true },
  { scheme: "photos-event://",            cat: "Apple Hidden", hidden: true },
  { scheme: "photos-navigation://",       cat: "Apple Hidden", hidden: true },
  { scheme: "com.apple.mobileslideshow://", cat: "Apple Hidden", hidden: true },
  { scheme: "x-apple-sosbuddy://",        cat: "Apple Hidden", hidden: true },
  { scheme: "telsos://",                  cat: "Apple Hidden", hidden: true },
  { scheme: "facetime-group://",          cat: "Apple Hidden", hidden: true },
  { scheme: "ens://",                     cat: "Apple Hidden", hidden: true },
  { scheme: "homeutil://",               cat: "Apple Hidden", hidden: true },
  { scheme: "x-argonaut-app://",          cat: "Apple Hidden", hidden: true },
  { scheme: "movietrailers://",           cat: "Apple Hidden", hidden: true },
  { scheme: "webclip://",                 cat: "Apple Hidden", hidden: true },
  { scheme: "webapp://",                  cat: "Apple Hidden", hidden: true },
  { scheme: "appstore-ui://",             cat: "Apple Hidden", hidden: true },
  { scheme: "itms-ui://",                 cat: "Apple Hidden", hidden: true },
  { scheme: "itms-services://",           cat: "Apple Hidden", hidden: true },
  { scheme: "macappstore://",             cat: "Apple Hidden", hidden: true },
  { scheme: "itms-watch://",             cat: "Apple Hidden", hidden: true },
  { scheme: "radar://",                   cat: "Apple Hidden", hidden: true },
  { scheme: "rdar://",                    cat: "Apple Hidden", hidden: true },
  { scheme: "x-tips-bulletin://",         cat: "Apple Hidden", hidden: true },
  { scheme: "x-tips-widget://",           cat: "Apple Hidden", hidden: true },
  { scheme: "iadoptout://",               cat: "Apple Hidden", hidden: true },
  { scheme: "safaridownloader://",        cat: "Apple Hidden", hidden: true },
  { scheme: "applestore-sec://",          cat: "Apple Hidden", hidden: true },
  { scheme: "applestore-alipay://",       cat: "Apple Hidden", hidden: true },
  { scheme: "itms-appss://",              cat: "Apple Hidden", hidden: true },
  { scheme: "esim://",                    cat: "Apple Hidden", hidden: true },
  { scheme: "otpauth-migration://",       cat: "Apple Hidden", hidden: true },
  { scheme: "apple-otpauth-migration://", cat: "Apple Hidden", hidden: true },
  { scheme: "tvremote://",               cat: "Apple Hidden", hidden: true },
  { scheme: "com.apple.Bridge://",        cat: "Apple Hidden", hidden: true },
  { scheme: "facegallery://",             cat: "Apple Hidden", hidden: true },
  { scheme: "moments://",                 cat: "Apple Hidden", hidden: true },
  { scheme: "x-maps-bulletin://",         cat: "Apple Hidden", hidden: true },
  { scheme: "x-maps-reopen://",           cat: "Apple Hidden", hidden: true },
  { scheme: "x-maps-route-genius://",     cat: "Apple Hidden", hidden: true },
  { scheme: "calinvite://",               cat: "Apple Hidden", hidden: true },
  { scheme: "calinvitelist://",           cat: "Apple Hidden", hidden: true },

  // ── PHONE & FACETIME ────────────────────────────────────────────────────
  { scheme: "tel://",            cat: "Phone & FaceTime" },
  { scheme: "telprompt://",      cat: "Phone & FaceTime" },
  { scheme: "mobilephone://",    cat: "Phone & FaceTime" },
  { scheme: "mobilephone-contacts://",  cat: "Phone & FaceTime" },
  { scheme: "mobilephone-favorites://", cat: "Phone & FaceTime" },
  { scheme: "mobilephone-recents://",   cat: "Phone & FaceTime" },
  { scheme: "mobilephone-unknowncallerstip://", cat: "Phone & FaceTime" },
  { scheme: "vmshow://",         cat: "Phone & FaceTime" },
  { scheme: "facetime://",       cat: "Phone & FaceTime" },
  { scheme: "facetime-audio://", cat: "Phone & FaceTime" },
  { scheme: "facetime-prompt://",       cat: "Phone & FaceTime" },
  { scheme: "facetime-audio-prompt://", cat: "Phone & FaceTime" },
  { scheme: "facetime-open-link://",    cat: "Phone & FaceTime" },

  // ── MESSAGES & MAIL ──────────────────────────────────────────────────────
  { scheme: "messages://",       cat: "Messages & Mail" },
  { scheme: "iChat://",          cat: "Messages & Mail" },
  { scheme: "im://",             cat: "Messages & Mail" },
  { scheme: "imessage://",       cat: "Messages & Mail" },
  { scheme: "sms://",            cat: "Messages & Mail" },
  { scheme: "sms-private://",    cat: "Messages & Mail" },
  { scheme: "itms-messages://",  cat: "Messages & Mail" },
  { scheme: "itms-messagess://", cat: "Messages & Mail" },
  { scheme: "mailto://",         cat: "Messages & Mail" },
  { scheme: "message://",        cat: "Messages & Mail" },

  // ── MAPS & NAVIGATION ──────────────────────────────────────────────────
  { scheme: "map://",            cat: "Maps & Navigation" },
  { scheme: "maps://",           cat: "Maps & Navigation" },
  { scheme: "mapitem://",        cat: "Maps & Navigation" },
  { scheme: "comgooglemaps://",  cat: "Maps & Navigation" },
  { scheme: "comgooglemaps-x-callback://", cat: "Maps & Navigation" },
  { scheme: "googlemaps://",     cat: "Maps & Navigation" },
  { scheme: "waze://",           cat: "Maps & Navigation" },
  { scheme: "citymapper://",     cat: "Maps & Navigation" },
  { scheme: "uber://",           cat: "Maps & Navigation" },
  { scheme: "lyft://",           cat: "Maps & Navigation" },
  { scheme: "transit://",        cat: "Maps & Navigation" },
  { scheme: "moovit://",         cat: "Maps & Navigation" },
  { scheme: "here-route://",     cat: "Maps & Navigation" },
  { scheme: "tomtomgo://",       cat: "Maps & Navigation" },
  { scheme: "navigon://",        cat: "Maps & Navigation" },

  // ── SHORTCUTS & AUTOMATION ──────────────────────────────────────────────
  { scheme: "shortcuts://",             cat: "Shortcuts & Automation" },
  { scheme: "shortcuts-production://",  cat: "Shortcuts & Automation" },
  { scheme: "workflow://",              cat: "Shortcuts & Automation" },
  { scheme: "shortcuts://create-shortcut",    cat: "Shortcuts & Automation", deep: true },
  { scheme: "shortcuts://gallery",            cat: "Shortcuts & Automation", deep: true },
  { scheme: "shortcuts://open-shortcut",      cat: "Shortcuts & Automation", deep: true },
  { scheme: "shortcuts://run-shortcut",       cat: "Shortcuts & Automation", deep: true },
  { scheme: "launch://",         cat: "Shortcuts & Automation" },
  { scheme: "launchpro://",      cat: "Shortcuts & Automation" },
  { scheme: "launchpro-dial://", cat: "Shortcuts & Automation" },
  { scheme: "launchpro-light://",cat: "Shortcuts & Automation" },
  { scheme: "ifttt://",          cat: "Shortcuts & Automation" },
  { scheme: "lifttt://",         cat: "Shortcuts & Automation" },
  { scheme: "launcher://",       cat: "Shortcuts & Automation" },
  { scheme: "mlauncher://",      cat: "Shortcuts & Automation" },

  // ── SETTINGS ────────────────────────────────────────────────────────────
  { scheme: "app-prefs://",             cat: "Settings" },
  { scheme: "prefs://",                 cat: "Settings" },
  { scheme: "prefs:root",               cat: "Settings" },
  { scheme: "com.apple.preferences://", cat: "Settings" },
  { scheme: "prefs:root=General",               cat: "Settings", deep: true },
  { scheme: "prefs:root=WIFI",                  cat: "Settings", deep: true },
  { scheme: "prefs:root=Bluetooth",             cat: "Settings", deep: true },
  { scheme: "prefs:root=NOTIFICATIONS_ID",      cat: "Settings", deep: true },
  { scheme: "prefs:root=Sounds",                cat: "Settings", deep: true },
  { scheme: "prefs:root=TOUCHID_PASSCODE",      cat: "Settings", deep: true },
  { scheme: "prefs:root=PRIVACY",               cat: "Settings", deep: true },
  { scheme: "prefs:root=LOCATION_SERVICES",     cat: "Settings", deep: true },
  { scheme: "prefs:root=ACCESSIBILITY",         cat: "Settings", deep: true },
  { scheme: "prefs:root=FACEID_PASSCODE",        cat: "Settings", deep: true },
  { scheme: "prefs:root=CASTLE",                cat: "Settings", deep: true },
  { scheme: "prefs:root=CASTLE&path=STORAGE_AND_BACKUP", cat: "Settings", deep: true },
  { scheme: "prefs:root=SAFARI",                cat: "Settings", deep: true },
  { scheme: "prefs:root=MUSIC",                 cat: "Settings", deep: true },
  { scheme: "prefs:root=TWITTER",               cat: "Settings", deep: true },
  { scheme: "prefs:root=FACEBOOK",              cat: "Settings", deep: true },
  { scheme: "prefs:root=WALLPAPER",             cat: "Settings", deep: true },
  { scheme: "prefs:root=DISPLAY",               cat: "Settings", deep: true },
  { scheme: "prefs:root=AIRPLANE_MODE",          cat: "Settings", deep: true },
  { scheme: "prefs:root=CELLULAR",              cat: "Settings", deep: true },
  { scheme: "prefs:root=Personal%20Hotspot",     cat: "Settings", deep: true },
  { scheme: "prefs:root=VPN",                   cat: "Settings", deep: true },
  { scheme: "prefs:root=DO_NOT_DISTURB",         cat: "Settings", deep: true },
  { scheme: "prefs:root=BATTERY_USAGE",          cat: "Settings", deep: true },
  { scheme: "prefs:root=STORE",                  cat: "Settings", deep: true },
  { scheme: "prefs:root=PASSWORDS",             cat: "Settings", deep: true },
  { scheme: "prefs:root=SCREEN_TIME",            cat: "Settings", deep: true },
  { scheme: "prefs:root=General&path=Keyboard",  cat: "Settings", deep: true },
  { scheme: "prefs:root=General&path=About",     cat: "Settings", deep: true },
  { scheme: "prefs:root=General&path=SOFTWARE_UPDATE_LINK", cat: "Settings", deep: true },

  // ── CALENDAR & REMINDERS ────────────────────────────────────────────────
  { scheme: "calshow://",         cat: "Calendar & Reminders" },
  { scheme: "x-apple-calevent://",cat: "Calendar & Reminders" },
  { scheme: "webcal://",          cat: "Calendar & Reminders" },
  { scheme: "x-apple-reminder://",cat: "Calendar & Reminders" },
  { scheme: "x-apple-reminderkit://", cat: "Calendar & Reminders" },

  // ── MUSIC & AUDIO ───────────────────────────────────────────────────────
  { scheme: "music://",           cat: "Music & Audio" },
  { scheme: "musics://",          cat: "Music & Audio" },
  { scheme: "audio-player-event://", cat: "Music & Audio" },
  { scheme: "itsradio://",        cat: "Music & Audio" },
  { scheme: "itsradios://",       cat: "Music & Audio" },
  { scheme: "itunesradio://",     cat: "Music & Audio" },
  { scheme: "itunesradios://",    cat: "Music & Audio" },
  { scheme: "spotify://",         cat: "Music & Audio" },
  { scheme: "pandora://",         cat: "Music & Audio" },
  { scheme: "pandorav2://",       cat: "Music & Audio" },
  { scheme: "pandorav3://",       cat: "Music & Audio" },
  { scheme: "pandorav4://",       cat: "Music & Audio" },
  { scheme: "soundcloud://",      cat: "Music & Audio" },
  { scheme: "garageband://",      cat: "Music & Audio" },
  { scheme: "mobilegarageband203.audiobus://", cat: "Music & Audio" },
  { scheme: "audioshare://",      cat: "Music & Audio" },
  { scheme: "audioshare.import://", cat: "Music & Audio" },
  { scheme: "audiosharecmd://",   cat: "Music & Audio" },
  { scheme: "audiocopyapp://",    cat: "Music & Audio" },
  { scheme: "audiocopyv3app://",  cat: "Music & Audio" },
  { scheme: "musicstudiolite://", cat: "Music & Audio" },
  { scheme: "djay://",            cat: "Music & Audio" },
  { scheme: "djay-iphone://",     cat: "Music & Audio" },
  { scheme: "djay-iphone-2://",   cat: "Music & Audio" },
  { scheme: "shazam://",          cat: "Music & Audio" },
  { scheme: "shazam-v8://",       cat: "Music & Audio" },
  { scheme: "shazamimporttags://",cat: "Music & Audio" },
  { scheme: "anytune://",         cat: "Music & Audio" },
  { scheme: "anytune-dl://",      cat: "Music & Audio" },
  { scheme: "anytune-p://",       cat: "Music & Audio" },
  { scheme: "loopy://",           cat: "Music & Audio" },
  { scheme: "loopy-hd://",        cat: "Music & Audio" },
  { scheme: "flstudiomobilehd://",cat: "Music & Audio" },
  { scheme: "smulesing://",       cat: "Music & Audio" },
  { scheme: "smuleautorap://",    cat: "Music & Audio" },
  { scheme: "tpain://",           cat: "Music & Audio" },

  // ── PHOTOS & VIDEO ──────────────────────────────────────────────────────
  { scheme: "photos://",          cat: "Photos & Video" },
  { scheme: "photos-redirect://", cat: "Photos & Video" },
  { scheme: "clips://",           cat: "Photos & Video" },
  { scheme: "camera://",          cat: "Photos & Video" },
  { scheme: "videos://",          cat: "Photos & Video" },
  { scheme: "imovie://",          cat: "Photos & Video" },
  { scheme: "imovie1.4://",       cat: "Photos & Video" },
  { scheme: "youtube://",         cat: "Photos & Video" },
  { scheme: "vnd.youtube://",     cat: "Photos & Video" },
  { scheme: "vnd.youtube-broad-matching://", cat: "Photos & Video" },
  { scheme: "hulu://",            cat: "Photos & Video" },
  { scheme: "plexapp://",         cat: "Photos & Video" },
  { scheme: "netflix://",         cat: "Photos & Video" },
  { scheme: "com.apple.tv://",    cat: "Photos & Video" },
  { scheme: "com.apple.WatchList://", cat: "Photos & Video" },
  { scheme: "videos://",          cat: "Photos & Video" },
  { scheme: "vlc://",             cat: "Photos & Video" },
  { scheme: "vlc-x-callback://",  cat: "Photos & Video" },
  { scheme: "moonvid://",         cat: "Photos & Video" },
  { scheme: "infuse://",          cat: "Photos & Video" },
  { scheme: "magisto://",         cat: "Photos & Video" },
  { scheme: "vidme://",           cat: "Photos & Video" },
  { scheme: "vidlab://",          cat: "Photos & Video" },

  // ── APP STORE & ITUNES ─────────────────────────────────────────────────
  { scheme: "itms-apps://itunes.apple.com",  cat: "App Store & iTunes" },
  { scheme: "itms://",            cat: "App Store & iTunes" },
  { scheme: "itmss://",           cat: "App Store & iTunes" },
  { scheme: "itms-beta://",       cat: "App Store & iTunes" },
  { scheme: "itms-itunesu://",    cat: "App Store & iTunes" },
  { scheme: "itms-itunesus://",   cat: "App Store & iTunes" },
  { scheme: "itms-podcast://",    cat: "App Store & iTunes" },
  { scheme: "itms-podcasts://",   cat: "App Store & iTunes" },
  { scheme: "itms-pcast://",      cat: "App Store & iTunes" },
  { scheme: "itms-pcasts://",     cat: "App Store & iTunes" },
  { scheme: "itms-books://",      cat: "App Store & iTunes" },
  { scheme: "itms-bookss://",     cat: "App Store & iTunes" },
  { scheme: "itms-gc://",         cat: "App Store & iTunes" },
  { scheme: "itms-gcs://",        cat: "App Store & iTunes" },
  { scheme: "applestore://",      cat: "App Store & iTunes" },

  // ── APPLE APPS ──────────────────────────────────────────────────────────
  { scheme: "calc://",            cat: "Apple Apps" },
  { scheme: "clock-alarm://",     cat: "Apple Apps" },
  { scheme: "clock-sleep-alarm://", cat: "Apple Apps" },
  { scheme: "clock-stopwatch://", cat: "Apple Apps" },
  { scheme: "clock-timer://",     cat: "Apple Apps" },
  { scheme: "clock-worldclock://",cat: "Apple Apps" },
  { scheme: "contact://",         cat: "Apple Apps" },
  { scheme: "people://",          cat: "Apple Apps" },
  { scheme: "diagnostics://",     cat: "Apple Apps" },
  { scheme: "diags://",           cat: "Apple Apps" },
  { scheme: "applefeedback://",   cat: "Apple Apps" },
  { scheme: "applefeedback://new",cat: "Apple Apps", deep: true },
  { scheme: "family://",          cat: "Apple Apps" },
  { scheme: "shareddocuments://", cat: "Apple Apps" },
  { scheme: "findmy://",          cat: "Apple Apps" },
  { scheme: "findmy://items",     cat: "Apple Apps", deep: true },
  { scheme: "findmyfriends://",   cat: "Apple Apps" },
  { scheme: "fmip1://",           cat: "Apple Apps" },
  { scheme: "fmf1://",            cat: "Apple Apps" },
  { scheme: "grenada://",         cat: "Apple Apps" },
  { scheme: "fitnessapp://",      cat: "Apple Apps" },
  { scheme: "activitytoday://",   cat: "Apple Apps" },
  { scheme: "activitysharing://", cat: "Apple Apps" },
  { scheme: "freeform://",        cat: "Apple Apps" },
  { scheme: "gamecenter://",      cat: "Apple Apps" },
  { scheme: "x-apple-health://",  cat: "Apple Apps" },
  { scheme: "x-apple-health://summary", cat: "Apple Apps", deep: true },
  { scheme: "x-apple-health://browse",  cat: "Apple Apps", deep: true },
  { scheme: "x-hm://",            cat: "Apple Apps" },
  { scheme: "ibooks://",          cat: "Apple Apps" },
  { scheme: "mobilenotes://",     cat: "Apple Apps" },
  { scheme: "applenotes://",      cat: "Apple Apps" },
  { scheme: "applenews://",       cat: "Apple Apps" },
  { scheme: "applenewss://",      cat: "Apple Apps" },
  { scheme: "pcast://",           cat: "Apple Apps" },
  { scheme: "podcasts://",        cat: "Apple Apps" },
  { scheme: "podcast://",         cat: "Apple Apps" },
  { scheme: "stocks://",          cat: "Apple Apps" },
  { scheme: "applesupport://",    cat: "Apple Apps" },
  { scheme: "shoebox://",         cat: "Apple Apps" },
  { scheme: "wallet://",          cat: "Apple Apps" },
  { scheme: "voicememos://",      cat: "Apple Apps" },
  { scheme: "x-web-search://",    cat: "Apple Apps" },
  { scheme: "remote://",          cat: "Apple Apps" },
  { scheme: "watchface://",       cat: "Apple Apps" },
  { scheme: "bridge://",          cat: "Apple Apps" },
  { scheme: "bridge:root=ActiveWatch", cat: "Apple Apps", deep: true },
  { scheme: "com.apple.tv://us/movie/", cat: "Apple Apps", deep: true },
  { scheme: "x-keynote-live://",  cat: "Apple Apps" },
  { scheme: "com.apple.iwork.keynote-live://", cat: "Apple Apps" },
  { scheme: "com.apple.iwork.numbers-share://", cat: "Apple Apps" },

  // ── SOCIAL MEDIA ────────────────────────────────────────────────────────
  { scheme: "twitter://",         cat: "Social Media" },
  { scheme: "twitterloginhome://",cat: "Social Media" },
  { scheme: "twittermusichome://",cat: "Social Media" },
  { scheme: "instagram://",       cat: "Social Media" },
  { scheme: "fb://",              cat: "Social Media" },
  { scheme: "fbauth://",          cat: "Social Media" },
  { scheme: "fbauth2://",         cat: "Social Media" },
  { scheme: "fblogin://",         cat: "Social Media" },
  { scheme: "fb-events-share://", cat: "Social Media" },
  { scheme: "fb-groups://",       cat: "Social Media" },
  { scheme: "fb-messenger://",    cat: "Social Media" },
  { scheme: "fb-messenger-share://", cat: "Social Media" },
  { scheme: "fb-messenger-voip://",  cat: "Social Media" },
  { scheme: "facebookloginhome://",  cat: "Social Media" },
  { scheme: "facebookmusichome://",  cat: "Social Media" },
  { scheme: "whatsapp://",        cat: "Social Media" },
  { scheme: "snapchat://",        cat: "Social Media" },
  { scheme: "tiktok://",          cat: "Social Media" },
  { scheme: "pinterest://",       cat: "Social Media" },
  { scheme: "linkedin://",        cat: "Social Media" },
  { scheme: "tumblr://",          cat: "Social Media" },
  { scheme: "reddit://",          cat: "Social Media" },
  { scheme: "telegram://",        cat: "Social Media" },
  { scheme: "discord://",         cat: "Social Media" },
  { scheme: "slack://",           cat: "Social Media" },
  { scheme: "signal://",          cat: "Social Media" },
  { scheme: "viber://",           cat: "Social Media" },
  { scheme: "line://",            cat: "Social Media" },
  { scheme: "wechat://",          cat: "Social Media" },
  { scheme: "skype://",           cat: "Social Media" },
  { scheme: "bereal://",          cat: "Social Media" },
  { scheme: "mastodon://",        cat: "Social Media" },
  { scheme: "threads://",         cat: "Social Media" },

  // ── PRODUCTIVITY ────────────────────────────────────────────────────────
  { scheme: "evernote://",        cat: "Productivity" },
  { scheme: "en://",              cat: "Productivity" },
  { scheme: "enx://",             cat: "Productivity" },
  { scheme: "evernotemsg://",     cat: "Productivity" },
  { scheme: "things://",          cat: "Productivity" },
  { scheme: "things2-iphone://",  cat: "Productivity" },
  { scheme: "twodo://",           cat: "Productivity" },
  { scheme: "twodo-widget://",    cat: "Productivity" },
  { scheme: "anydo://",           cat: "Productivity" },
  { scheme: "anydoNewVersion://", cat: "Productivity" },
  { scheme: "omnifocus://",       cat: "Productivity" },
  { scheme: "omnioutliner://",    cat: "Productivity" },
  { scheme: "omnigraffle://",     cat: "Productivity" },
  { scheme: "omniplan://",        cat: "Productivity" },
  { scheme: "drafts4://",         cat: "Productivity" },
  { scheme: "x-drafts4://",       cat: "Productivity" },
  { scheme: "byword://",          cat: "Productivity" },
  { scheme: "editorial://",       cat: "Productivity" },
  { scheme: "1password://",       cat: "Productivity" },
  { scheme: "onepassword://",     cat: "Productivity" },
  { scheme: "onepassword4://",    cat: "Productivity" },
  { scheme: "ophttp://",          cat: "Productivity" },
  { scheme: "ophttps://",         cat: "Productivity" },
  { scheme: "simplenote://",      cat: "Productivity" },
  { scheme: "notion://",          cat: "Productivity" },
  { scheme: "obsidian://",        cat: "Productivity" },
  { scheme: "bear://",            cat: "Productivity" },
  { scheme: "craft://",           cat: "Productivity" },
  { scheme: "goodlinks://",       cat: "Productivity" },
  { scheme: "reeder://",          cat: "Productivity" },
  { scheme: "feedly://",          cat: "Productivity" },
  { scheme: "swipes://",          cat: "Productivity" },
  { scheme: "mindnode://",        cat: "Productivity" },
  { scheme: "daedalus://",        cat: "Productivity" },
  { scheme: "nocs://",            cat: "Productivity" },
  { scheme: "listacular://",      cat: "Productivity" },
  { scheme: "tally2://",          cat: "Productivity" },
  { scheme: "countdown://",       cat: "Productivity" },
  { scheme: "amount://",          cat: "Productivity" },
  { scheme: "carlogbook://",      cat: "Productivity" },
  { scheme: "command-c://",       cat: "Productivity" },
  { scheme: "tetouch://",         cat: "Productivity" },
  { scheme: "tetouch-settings://",cat: "Productivity" },
  { scheme: "short-menu://",      cat: "Productivity" },

  // ── CLOUD STORAGE ───────────────────────────────────────────────────────
  { scheme: "googledrive://",     cat: "Cloud Storage" },
  { scheme: "googledrive-v1://",  cat: "Cloud Storage" },
  { scheme: "googledrive-v2://",  cat: "Cloud Storage" },
  { scheme: "googledrive-v3://",  cat: "Cloud Storage" },
  { scheme: "googledocs://",      cat: "Cloud Storage" },
  { scheme: "googledocs-v2://",   cat: "Cloud Storage" },
  { scheme: "googlegmail://",     cat: "Cloud Storage" },
  { scheme: "googlegmail-x-callback://", cat: "Cloud Storage" },
  { scheme: "ms-onedrive://",     cat: "Cloud Storage" },
  { scheme: "ms-onedrive-intunemam://", cat: "Cloud Storage" },
  { scheme: "dbapi-1://",         cat: "Cloud Storage" },
  { scheme: "dbapi-2://",         cat: "Cloud Storage" },
  { scheme: "dbapi-3://",         cat: "Cloud Storage" },
  { scheme: "db-auth://",         cat: "Cloud Storage" },
  { scheme: "boxapp://",          cat: "Cloud Storage" },
  { scheme: "smb://",             cat: "Cloud Storage" },
  { scheme: "ftp://",             cat: "Cloud Storage" },
  { scheme: "sftp://",            cat: "Cloud Storage" },

  // ── OFFICE & DOCUMENTS ──────────────────────────────────────────────────
  { scheme: "open-word://",        cat: "Office & Documents" },
  { scheme: "launch-word://",      cat: "Office & Documents" },
  { scheme: "ms-excel://",         cat: "Office & Documents" },
  { scheme: "ms-powerpoint://",    cat: "Office & Documents" },
  { scheme: "ms-word://",          cat: "Office & Documents" },
  { scheme: "ms-outlook://",       cat: "Office & Documents" },
  { scheme: "ms-teams://",         cat: "Office & Documents" },
  { scheme: "ms-onenote://",       cat: "Office & Documents" },
  { scheme: "notability://",       cat: "Office & Documents" },
  { scheme: "documents://",        cat: "Office & Documents" },
  { scheme: "pdfexpert://",        cat: "Office & Documents" },
  { scheme: "goodreader://",       cat: "Office & Documents" },
  { scheme: "goodreader4://",      cat: "Office & Documents" },
  { scheme: "izip://",             cat: "Office & Documents" },
  { scheme: "textastic://",        cat: "Office & Documents" },
  { scheme: "prompt-ssh://",       cat: "Office & Documents" },
  { scheme: "ssh://",              cat: "Office & Documents" },
  { scheme: "telnet://",           cat: "Office & Documents" },
  { scheme: "vnc://",              cat: "Office & Documents" },

  // ── BROWSERS ─────────────────────────────────────────────────────────────
  { scheme: "http://",             cat: "Browsers" },
  { scheme: "https://",            cat: "Browsers" },
  { scheme: "googlechrome://",     cat: "Browsers" },
  { scheme: "googlechromes://",    cat: "Browsers" },
  { scheme: "firefox://",          cat: "Browsers" },
  { scheme: "firefox-x-callback://", cat: "Browsers" },
  { scheme: "opera://",            cat: "Browsers" },
  { scheme: "openhttps://",        cat: "Browsers" },
  { scheme: "icabmobile://",       cat: "Browsers" },
  { scheme: "web://",              cat: "Browsers" },
  { scheme: "webs://",             cat: "Browsers" },
  { scheme: "webconfig://",        cat: "Browsers" },
  { scheme: "dolphin://",          cat: "Browsers" },
  { scheme: "brave://",            cat: "Browsers" },
  { scheme: "ddgQuickLink://",     cat: "Browsers" },

  // ── DEVELOPER & SECURITY ────────────────────────────────────────────────
  { scheme: "pythonista://",       cat: "Developer" },
  { scheme: "codecademy://",       cat: "Developer" },
  { scheme: "googleauthenticator://", cat: "Developer" },
  { scheme: "otpauth://",          cat: "Developer" },
  { scheme: "apple-otpauth://",    cat: "Developer" },
  { scheme: "totp://",             cat: "Developer" },
  { scheme: "mms://",              cat: "Developer" },
  { scheme: "rtsp://",             cat: "Developer" },
  { scheme: "rtmp://",             cat: "Developer" },
  { scheme: "rtp://",              cat: "Developer" },
  { scheme: "udp://",              cat: "Developer" },
  { scheme: "vnc://",              cat: "Developer" },
  { scheme: "ifile://",            cat: "Developer" },
  { scheme: "cydia://",            cat: "Developer" },
  { scheme: "activator://",        cat: "Developer" },
  { scheme: "icleaner://",         cat: "Developer" },

  // ── FITNESS & HEALTH ────────────────────────────────────────────────────
  { scheme: "fitnessapp://",       cat: "Fitness & Health" },
  { scheme: "myfitnesspal://",     cat: "Fitness & Health" },
  { scheme: "runkeeper://",        cat: "Fitness & Health" },
  { scheme: "strava://",           cat: "Fitness & Health" },
  { scheme: "nike://",             cat: "Fitness & Health" },
  { scheme: "abvio-walkmeter://",  cat: "Fitness & Health" },
  { scheme: "sc1337://",           cat: "Fitness & Health" },
  { scheme: "fitbrains-trainer://",cat: "Fitness & Health" },
  { scheme: "peloton://",          cat: "Fitness & Health" },
  { scheme: "headspace://",        cat: "Fitness & Health" },
  { scheme: "calm://",             cat: "Fitness & Health" },
  { scheme: "whoop://",            cat: "Fitness & Health" },

  // ── FINANCE ─────────────────────────────────────────────────────────────
  { scheme: "venmo://",            cat: "Finance" },
  { scheme: "paypal://",           cat: "Finance" },
  { scheme: "cashapp://",          cat: "Finance" },
  { scheme: "coinbase://",         cat: "Finance" },
  { scheme: "robinhood://",        cat: "Finance" },
  { scheme: "capitalone://",       cat: "Finance" },
  { scheme: "com.capitalone.ease://", cat: "Finance" },
  { scheme: "expensesok://",       cat: "Finance" },

  // ── TRAVEL & TRANSPORT ──────────────────────────────────────────────────
  { scheme: "airbnb://",           cat: "Travel" },
  { scheme: "yelp://",             cat: "Travel" },
  { scheme: "opentable://",        cat: "Travel" },
  { scheme: "tripadvisor://",      cat: "Travel" },
  { scheme: "dominos://",          cat: "Travel" },
  { scheme: "dominospizza://",     cat: "Travel" },

  // ── GAMES ────────────────────────────────────────────────────────────────
  { scheme: "angrybirds-seasons://", cat: "Games" },
  { scheme: "gamecenter://",       cat: "Games" },
  { scheme: "itms-gc://",          cat: "Games" },
  { scheme: "itms-gcs://",         cat: "Games" },
  { scheme: "alienblue://",        cat: "Games" },
  { scheme: "starwalk://",         cat: "Games" },
  { scheme: "starwalk2://",        cat: "Games" },

  // ── MISC / OTHER ────────────────────────────────────────────────────────
  { scheme: "iTranslate://",       cat: "Misc" },
  { scheme: "itranslate://",       cat: "Misc" },
  { scheme: "itranslatevoice://",  cat: "Misc" },
  { scheme: "translatorfreenew://",cat: "Misc" },
  { scheme: "googletranslate://",  cat: "Misc" },
  { scheme: "pocketcloudpartner://", cat: "Misc" },
  { scheme: "RemoteMouse://",      cat: "Misc" },
  { scheme: "launch-word://",      cat: "Misc" },
  { scheme: "historyhere://",      cat: "Misc" },
  { scheme: "timehop://",          cat: "Misc" },
  { scheme: "NPROne://",           cat: "Misc" },
  { scheme: "nprone://",           cat: "Misc" },
  { scheme: "pandora://",          cat: "Misc" },
  { scheme: "photogrid://",        cat: "Misc" },
  { scheme: "cameraplus://",       cat: "Misc" },
  { scheme: "camplus://",          cat: "Misc" },
  { scheme: "camplusfull://",      cat: "Misc" },
  { scheme: "colorsplash://",      cat: "Misc" },
  { scheme: "juxtaposer://",       cat: "Misc" },
  { scheme: "giffer://",           cat: "Misc" },
  { scheme: "swiftkey://",         cat: "Misc" },
  { scheme: "burnernumber://",     cat: "Misc" },
  { scheme: "burner://",           cat: "Misc" },
  { scheme: "pocketapp://",        cat: "Misc" },
  { scheme: "readkit://",          cat: "Misc" },
  { scheme: "instapaper://",       cat: "Misc" },
  { scheme: "pocket://",           cat: "Misc" },
  { scheme: "plexamp://",          cat: "Misc" },
  { scheme: "irecorder://",        cat: "Misc" },
  { scheme: "iRec://",             cat: "Misc" },
  { scheme: "appcake://",          cat: "Misc" },
];
